version: "3.9"

services:

  backend:
    image: fallmodo/diabete-backend:1.0.0
    ports:
      - "8000:8000"
    networks:
      - backend_net
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  frontend:
    image: fallmodo/diabete-frontend:1.0.0
    ports:
      - "3000:80"
    networks:
      - frontend_net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: diabetes_user
      POSTGRES_PASSWORD: diabetes_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:7-alpine
    networks:
      - backend_net
    deploy:
      replicas: 1

  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  postgres_data:

networks:
  backend_net:
    driver: overlay
  frontend_net:
    driver: overlay
