version: "3.9"

services:

  # ================================
  # NGINX REVERSE PROXY
  # ================================
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - frontend_net
      - backend_net



  # ================================
  # FRONTEND
  # ================================
  frontend:
    image: fallmodo/diabete-frontend:1.0.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - frontend_net

  # ================================
  # BACKEND
  # ================================
  backend:
    image: 192.168.1.18:5000/diabete-backend:1.0.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: diabetes_user
      POSTGRES_PASSWORD: diabetes_pass
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - backend_net

  # ================================
  # POSTGRES
  # ================================
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: diabetes_user
      POSTGRES_PASSWORD: diabetes_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - backend_net

  # ================================
  # REDIS
  # ================================
  redis:
    image: redis:7-alpine
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend_net


# ================================
# VISUALIZER
# ================================
  visualizer:
     image: dockersamples/visualizer:latest
     ports:
       - "8089:8080"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     deploy:
       placement:
         constraints:
           - node.role == manager
       replicas: 1
       restart_policy:
         condition: any




# ================================
# CONFIGS
# ================================
configs:
  nginx_conf:
    file: swarm-nginx/nginx.conf

# ================================
# VOLUMES
# ================================
volumes:
  postgres_data:

# ================================
# NETWORKS
# ================================
networks:
  frontend_net:
    driver: overlay
  backend_net:
    driver: overlay
