version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7-alpine
    networks:
      - backend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: diabete-backend:1.0.0
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    networks:
      - backend_net
      - frontend_net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: diabete-frontend:1.0.0
    ports:
      - "3000:80"
    networks:
      - frontend_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file: .env
    ports:
      - "5050:80"
    networks:
      - backend_net
    deploy:
      replicas: 1

volumes:
  postgres_data:

networks:
  frontend_net:
  backend_net:
